"""Physically-parameterized bonded terms: Morse bonds and cosine angles.

This replaces the NN bond-energy head (:mod:`rsfff.ff.bond_energy`) with the pyCMM functional
forms whose *parameters* are generated by the conditioned network:

    V_bond(r)      = D [ (1 - e^{-beta (r - r_eq)})^2 - 1 ],    beta = sqrt(k / 2D)
    V_angle(theta) = (k_theta / 2) (cos theta - cos theta_eq)^2

Two deliberate choices relative to pyCMM (``~/dev/pyCMM/cmm/bonded.py``):

1. **The Morse is well-referenced** -- the ``- 1`` -- so the bond carries its dissociation
   energy: ``fragment_energy -> sum_i E0[Z_i]`` exactly as the bonds break, and ``D`` is the
   literal well depth rather than a shape parameter next to an unexplained constant. pyCMM's
   zero-at-minimum form pushes the atomization energy into terms that have nowhere physical
   to put it. (This is the one deviation from the user-specified literal formula, made so the
   isolated-fragment energy labels are representable at all.)
2. **No bilinear couplings and no explicit charge flux.** pyCMM needs bond-bond, stretch-bend
   and flux terms because its parameters are constants; here every parameter is a function of
   the fragment's geometry through the features, which carries those couplings implicitly.
   The geometry-independence regularizer (the ``delta_iso`` outputs below) is what keeps that
   flexibility from degenerating into "the parameters are a disguised pair energy".

``beta = sqrt(k / 2D)`` ties the harmonic curvature to the well depth (pyCMM
``system.py:712``), so the network predicts ``(r_eq, D, k)`` and the anharmonicity stays
physical by construction.

The bond/angle **topology comes from the fragment assignment and composition, never from a
distance rule** -- the same invariant the SQE channel graph keeps. Bonds are the heavy-H and
heavy-heavy pairs inside each fragment (H-H is never a bond); angles are enumerated from bonds
sharing an atom. A stretched bond therefore cannot fall out of its own term.

Units: this module works in **atomic units** throughout (bohr, hartree). The model converts
its Angstrom geometry once at the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn as nn

from ...mlip.heads import mlp, zero_init_readout
from ..pairs import intra_fragment_channels
from ..units import BOHR_ANG
from .state import StateDescriptor

__all__ = [
    "BondedParameterHead",
    "BondedParameters",
    "BondedTopology",
    "DEFAULT_ANGLE_PRIOR",
    "DEFAULT_BOND_PRIOR",
    "cosine_angle_energy",
    "morse_energy",
]


# pyCMM water (scripts/water.xml), atomic units: the validated starting point. Keys are
# unordered atomic-number pairs for bonds and the apex atomic number for angles. Pairs not
# listed fall back to GENERIC_*, which only matters once fragments beyond water appear.
DEFAULT_BOND_PRIOR: dict[tuple[int, int], tuple[float, float, float]] = {
    # (Z_a, Z_b) sorted: (r_eq [bohr], D [Ha], k [Ha/bohr^2])
    (1, 8): (1.81211318, 0.19968199, 0.54375456),
}
GENERIC_BOND_PRIOR: tuple[float, float, float] = (2.2, 0.15, 0.40)

DEFAULT_ANGLE_PRIOR: dict[int, tuple[float, float]] = {
    # apex Z: (theta_eq [rad], k_theta [Ha])
    8: (1.822532146, 0.1722274),
}
GENERIC_ANGLE_PRIOR: tuple[float, float] = (1.911, 0.15)


def morse_energy(
    r: torch.Tensor, r_eq: torch.Tensor, d: torch.Tensor, k: torch.Tensor
) -> torch.Tensor:
    """Well-referenced Morse: ``D [(1 - e^{-beta (r - r_eq)})^2 - 1]``, ``beta = sqrt(k/2D)``.

    Zero as ``r -> inf`` and ``-D`` at the minimum, so the sum over bonds is (minus) the
    energy of formation relative to the separated-atom reference. All inputs in a.u.
    """
    beta = torch.sqrt(k / (2.0 * d))
    x = 1.0 - torch.exp(-beta * (r - r_eq))
    return d * (x * x - 1.0)


def cosine_angle_energy(
    cos_theta: torch.Tensor, cos_theta_eq: torch.Tensor, k_theta: torch.Tensor
) -> torch.Tensor:
    """``(k_theta / 2)(cos theta - cos theta_eq)^2`` -- pyCMM's cosine-harmonic angle.

    Works on cosines throughout (no ``acos``), so it is smooth through linear geometries and
    the gradient needs no special-casing at ``theta = pi``.
    """
    diff = cos_theta - cos_theta_eq
    return 0.5 * k_theta * diff * diff


def _angles_from_bonds(bond_index: torch.Tensor, n_atoms: int) -> torch.Tensor:
    """``(3, Na)`` rows ``[i, apex, k]``: every pair of bonds sharing an atom.

    Vectorized with the same padded-triangle trick as
    :func:`rsfff.ff.pairs.intra_fragment_channels`: build the (atom -> bonded neighbor)
    incidence sorted by atom, enumerate the upper triangle of the largest degree once, and
    mask each atom down to its own degree.
    """
    if bond_index.shape[1] == 0:
        return torch.zeros(3, 0, dtype=torch.long, device=bond_index.device)
    device = bond_index.device
    atoms = torch.cat((bond_index[0], bond_index[1]))
    others = torch.cat((bond_index[1], bond_index[0]))
    order = torch.argsort(atoms, stable=True)
    atoms_s, others_s = atoms[order], others[order]
    counts = torch.bincount(atoms_s, minlength=n_atoms)
    deg_max = int(counts.max())
    if deg_max < 2:
        return torch.zeros(3, 0, dtype=torch.long, device=device)
    offsets = torch.cumsum(counts, 0) - counts                       # (n_atoms,)
    a, b = torch.triu_indices(deg_max, deg_max, offset=1, device=device)
    keep = b.unsqueeze(0) < counts.unsqueeze(1)                      # (n_atoms, K)
    first = (offsets.unsqueeze(1) + a.unsqueeze(0))[keep]
    second = (offsets.unsqueeze(1) + b.unsqueeze(0))[keep]
    apex = (
        torch.arange(n_atoms, device=device).unsqueeze(1).expand(-1, a.numel())[keep]
    )
    return torch.stack((others_s[first], apex, others_s[second]))


@dataclass
class BondedTopology:
    """The covalent graph of one batch under one fragmentation state.

    ``bond_index``  : (2, Nb) atom pairs, ``i < j``.
    ``bond_frag``   : (Nb,) owning fragment (of the first atom; identical at one-hot ``C``).
    ``bond_weight`` : (Nb,) co-membership ``P_ij`` -- 1.0 at a one-hot assignment, fractional
                      along a state blend, which is the reactive-phase extension point
                      (a union of candidate bonded terms with continuous amplitudes).
    ``angle_index`` : (3, Na) rows ``[i, apex, k]``.
    ``angle_frag``  : (Na,) owning fragment of the apex.
    ``angle_weight``: (Na,) ``P_{i,apex} P_{apex,k}``.
    """

    bond_index: torch.Tensor
    bond_frag: torch.Tensor
    bond_weight: torch.Tensor
    angle_index: torch.Tensor
    angle_frag: torch.Tensor
    angle_weight: torch.Tensor

    @classmethod
    def from_state(
        cls, state: StateDescriptor, atomic_numbers: torch.Tensor
    ) -> "BondedTopology":
        """Enumerate bonds and angles from the assignment -- no distance anywhere.

        Bonds are every intra-fragment pair that is not H-H; angles come from bonds sharing
        an atom. For a water that is exactly 2 x (O, H) and 1 x (H, O, H).
        """
        n_atoms = int(atomic_numbers.shape[0])
        pairs, pair_frag = intra_fragment_channels(state.fragment_idx)
        is_h = atomic_numbers == 1
        keep = ~(is_h[pairs[0]] & is_h[pairs[1]])
        bond_index = pairs[:, keep]
        bond_frag = pair_frag[keep]
        bond_weight = state.edge_comembership(bond_index)

        angle_index = _angles_from_bonds(bond_index, n_atoms)
        angle_frag = state.fragment_idx[angle_index[1]]
        i, apex, k = angle_index[0], angle_index[1], angle_index[2]
        angle_weight = (state.C[i] * state.C[apex]).sum(-1) * (
            state.C[apex] * state.C[k]
        ).sum(-1)
        return cls(
            bond_index=bond_index,
            bond_frag=bond_frag,
            bond_weight=bond_weight,
            angle_index=angle_index,
            angle_frag=angle_frag,
            angle_weight=angle_weight,
        )

    def geometry(self, positions_ang: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """``(r_bohr (Nb,), cos_theta (Na,))`` from Angstrom positions, differentiably."""
        i, j = self.bond_index[0], self.bond_index[1]
        r = (positions_ang[i] - positions_ang[j]).norm(dim=-1) / BOHR_ANG
        a, apex, c = self.angle_index[0], self.angle_index[1], self.angle_index[2]
        v1 = positions_ang[a] - positions_ang[apex]
        v2 = positions_ang[c] - positions_ang[apex]
        cos_theta = (v1 * v2).sum(-1) / (v1.norm(dim=-1) * v2.norm(dim=-1))
        return r, cos_theta


@dataclass
class BondedParameters:
    """One evaluation's bonded parameters plus the raw deviations the regularizer reads.

    ``r_eq, d, k``          : (Nb,) Morse parameters, a.u.
    ``cos_theta_eq, k_theta``: (Na,) angle parameters.
    ``delta_iso``           : flat tensor of the feature-dependent log/raw deviations from
                              the per-type tables at the *isolated* branch -- the quantity the
                              geometry-independence penalty pulls toward zero. (The env
                              deviation is governed by the induction label and the L1 env
                              penalty instead, and is not included here.)
    """

    r_eq: torch.Tensor
    d: torch.Tensor
    k: torch.Tensor
    cos_theta_eq: torch.Tensor
    k_theta: torch.Tensor
    delta_iso: torch.Tensor | None = None

    def energy(
        self, r: torch.Tensor, cos_theta: torch.Tensor, topo: BondedTopology
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """``(per-bond (Nb,), per-angle (Na,))`` energies, co-membership weighted."""
        e_bond = topo.bond_weight * morse_energy(r, self.r_eq, self.d, self.k)
        e_angle = topo.angle_weight * cosine_angle_energy(
            cos_theta, self.cos_theta_eq, self.k_theta
        )
        return e_bond, e_angle


class BondedParameterHead(nn.Module):
    """Per-bond ``(r_eq, D, k)`` and per-angle ``(theta_eq, k_theta)`` from the latents.

    Every parameter is ``table[type] * exp(delta_iso + gate * delta_env)`` (positives) or
    ``tanh(table[type] + delta_iso + gate * delta_env)`` (``cos theta_eq``), with:

    - a **learnable per-type table** initialized at the pyCMM water values, so a fresh model
      *is* pyCMM water and the readouts start at exactly zero deviation;
    - ``delta_iso`` from the isolated latent -- the geometry dependence the variance
      regularizer disciplines;
    - ``delta_env`` from the joined latent, zero-initialized and multiplied by the
      environment gate, so it vanishes exactly for an isolated fragment. Its energy lands in
      the induction channel (``E_bonded(theta) - E_bonded(theta_0)``) -- the learned analogue
      of pyCMM's field-dependent Morse.

    **Geometry enters only through the features.** The heads never see ``r`` or ``theta``;
    feeding them the coordinate a parameter multiplies would make the "parameter" a disguised
    pair energy and the physical form a fiction.

    Inputs are symmetric functions of the endpoint latents (``z_i + z_j``, ``(z_i - z_j)^2``
    -- squared, not ``| |``, so the symmetric-geometry point is smooth), which makes the
    parameters invariant under within-fragment permutation of identical atoms by
    construction.
    """

    def __init__(
        self,
        latent_dim: int,
        species: list[int],
        *,
        hidden: int = 64,
        depth: int = 1,
        emb_dim: int = 8,
        bond_prior: dict[tuple[int, int], tuple[float, float, float]] | None = None,
        angle_prior: dict[int, tuple[float, float]] | None = None,
    ) -> None:
        super().__init__()
        self.species = [int(z) for z in species]
        n_species = len(self.species)

        bond_prior = dict(DEFAULT_BOND_PRIOR, **(bond_prior or {}))
        angle_prior = dict(DEFAULT_ANGLE_PRIOR, **(angle_prior or {}))

        # (n_species, n_species, 3) log-parameter table, symmetric by construction (filled
        # for both orderings). Learnable: the table is the geometry-independent part of every
        # parameter, i.e. the analytic minimum of the variance penalty.
        table = torch.empty(n_species, n_species, 3)
        for ia, za in enumerate(self.species):
            for ib, zb in enumerate(self.species):
                key = (min(za, zb), max(za, zb))
                r_eq, d, k = bond_prior.get(key, GENERIC_BOND_PRIOR)
                table[ia, ib] = torch.tensor([r_eq, d, k]).log()
        self.bond_table = nn.Parameter(table)

        # (n_species, 2): [atanh(cos theta_eq), log k_theta] per apex species.
        atable = torch.empty(n_species, 2)
        for ia, za in enumerate(self.species):
            theta_eq, k_theta = angle_prior.get(za, GENERIC_ANGLE_PRIOR)
            atable[ia, 0] = torch.atanh(torch.tensor(theta_eq).cos())
            atable[ia, 1] = torch.tensor(k_theta).log()
        self.angle_table = nn.Parameter(atable)

        self.species_emb = nn.Embedding(n_species, emb_dim)
        bond_in = 2 * latent_dim + 2 * emb_dim
        angle_in = 3 * latent_dim + 3 * emb_dim
        self.bond_base = zero_init_readout(mlp(bond_in, hidden, depth, 3))
        self.bond_delta = zero_init_readout(mlp(bond_in, hidden, depth, 3))
        self.angle_base = zero_init_readout(mlp(angle_in, hidden, depth, 2))
        self.angle_delta = zero_init_readout(mlp(angle_in, hidden, depth, 2))

    def _bond_input(self, z: torch.Tensor, species_idx: torch.Tensor, topo) -> torch.Tensor:
        i, j = topo.bond_index[0], topo.bond_index[1]
        emb = self.species_emb(species_idx)
        zi, zj = z[i], z[j]
        return torch.cat(
            ((zi + zj), (zi - zj) ** 2, emb[i] + emb[j], (emb[i] - emb[j]) ** 2), dim=-1
        )

    def _angle_input(self, z: torch.Tensor, species_idx: torch.Tensor, topo) -> torch.Tensor:
        a, apex, c = topo.angle_index[0], topo.angle_index[1], topo.angle_index[2]
        emb = self.species_emb(species_idx)
        za, zc = z[a], z[c]
        return torch.cat(
            (
                z[apex], (za + zc), (za - zc) ** 2,
                emb[apex], emb[a] + emb[c], (emb[a] - emb[c]) ** 2,
            ),
            dim=-1,
        )

    def forward(
        self,
        z_iso: torch.Tensor,          # (N, latent)
        z_joined: torch.Tensor | None,  # (N, latent) or None for the isolated evaluation
        gate: torch.Tensor | None,    # (N,) environment gate g(a_env), g(0) = 0
        species_idx: torch.Tensor,    # (N,)
        topo: BondedTopology,
    ) -> BondedParameters:
        """Parameters at one evaluation. ``z_joined=None`` gives ``theta_0`` exactly.

        Note ``theta_0`` needs no separate machinery: the delta branch is *multiplied by the
        gate*, so on an isolated fragment ``theta == theta_0`` bitwise regardless of weights.
        """
        bond_x_iso = self._bond_input(z_iso, species_idx, topo)
        angle_x_iso = self._angle_input(z_iso, species_idx, topo)
        d_bond = self.bond_base(bond_x_iso)                        # (Nb, 3)
        d_angle = self.angle_base(angle_x_iso)                     # (Na, 2)
        delta_iso = torch.cat((d_bond.reshape(-1), d_angle.reshape(-1)))

        if z_joined is not None:
            if gate is None:
                raise ValueError("the env-dressed evaluation needs the environment gate")
            i, j = topo.bond_index[0], topo.bond_index[1]
            g_bond = 0.5 * (gate[i] + gate[j])
            a, apex, c = topo.angle_index[0], topo.angle_index[1], topo.angle_index[2]
            g_angle = (gate[a] + gate[apex] + gate[c]) / 3.0
            d_bond = d_bond + g_bond.unsqueeze(-1) * self.bond_delta(
                self._bond_input(z_joined, species_idx, topo)
            )
            d_angle = d_angle + g_angle.unsqueeze(-1) * self.angle_delta(
                self._angle_input(z_joined, species_idx, topo)
            )

        si = species_idx[topo.bond_index[0]]
        sj = species_idx[topo.bond_index[1]]
        log_bond = self.bond_table[si, sj] + d_bond                # (Nb, 3)
        r_eq, d, k = log_bond.exp().unbind(-1)

        s_apex = species_idx[topo.angle_index[1]]
        raw_angle = self.angle_table[s_apex] + d_angle             # (Na, 2)
        cos_theta_eq = torch.tanh(raw_angle[:, 0])
        k_theta = raw_angle[:, 1].exp()

        return BondedParameters(
            r_eq=r_eq, d=d, k=k,
            cos_theta_eq=cos_theta_eq, k_theta=k_theta,
            delta_iso=delta_iso,
        )
