"""Physically-parameterized bonded terms: Morse bonds, cosine angles, out-of-plane impropers.

This replaces the NN bond-energy head (:mod:`rsfff.ff.bond_energy`) with the pyCMM functional
forms whose *parameters* are generated by the conditioned network:

    V_bond(r)      = D [ (1 - e^{-beta (r - r_eq)})^2 - 1 ],    beta = sqrt(k / 2D)
    V_angle(theta) = (k_theta / 2) (cos theta - cos theta_eq)^2

Two deliberate choices relative to pyCMM (``~/dev/pyCMM/cmm/bonded.py``):

1. **The Morse is well-referenced** -- the ``- 1`` -- so the bond carries its dissociation
   energy: ``fragment_energy -> sum_i E0[Z_i]`` exactly as the bonds break, and ``D`` is the
   literal well depth rather than a shape parameter next to an unexplained constant. pyCMM's
   zero-at-minimum form pushes the atomization energy into terms that have nowhere physical
   to put it. (This is the one deviation from the user-specified literal formula, made so the
   isolated-fragment energy labels are representable at all.)
2. **No bilinear couplings and no explicit charge flux.** pyCMM needs bond-bond, stretch-bend
   and flux terms because its parameters are constants; here every parameter is a function of
   the fragment's geometry through the features, which carries those couplings implicitly.
   The geometry-independence regularizer (the ``delta_iso`` outputs below) is what keeps that
   flexibility from degenerating into "the parameters are a disguised pair energy".

``beta = sqrt(k / 2D)`` ties the harmonic curvature to the well depth (pyCMM
``system.py:712``), so the network predicts ``(r_eq, D, k)`` and the anharmonicity stays
physical by construction.

The bond/angle **topology comes from the fragment assignment and composition, never from a
distance rule** -- the same invariant the SQE channel graph keeps. Bonds are the heavy-H and
heavy-heavy pairs inside each fragment (H-H is never a bond); angles are enumerated from bonds
sharing an atom. A stretched bond therefore cannot fall out of its own term.

**Impropers (opt-in, ``impropers=True`` on the head).** Every atom with exactly three
bonded neighbors (the N of NH3, the O of H3O+) also carries one out-of-plane term per leg,
in the Wilson angle ``chi_l`` between leg ``l`` and the plane of the other two legs::

    s_l   = sin^2 chi_l = [b_l . (b_j x b_k)]^2 / |b_j x b_k|^2   (b: unit bonds from the center)
    V_imp = (k_chi / 2) s_l (s_l - 2 c_chi),        c_chi in (-1, 1),  k_chi > 0

i.e. ``(k_chi/2)[(s - c_chi)^2 - c_chi^2]``: zero at planarity, a polynomial in the squared
triple product. Three properties decide the form:

- **even in chi.** The two pyramidal minima of NH3 are mirror images and must be degenerate;
  a CHARMM-style harmonic improper ``k (omega - omega_0)^2`` with ``omega_0 != 0`` gives the
  inverted molecule a different energy (and depends on atom ordering), so it cannot
  describe inversion.
- **permutation-invariant.** Each leg's term is symmetric in its two in-plane partners, and
  all three legs are summed.
- **smooth everywhere the angle term is.** No ``asin``/``sqrt``; the only singular point is
  ``b_j || b_k`` (a linear J-center-K), guarded by an epsilon.

``c_chi`` is deliberately *not* confined to ``[0, 1]`` (it is not ``sin^2`` of an equilibrium
angle). ``c_chi > 0`` is a symmetric double well with minima at ``s = c_chi`` and a planar
barrier ``k c^2 / 2`` per leg; ``c_chi < 0`` is a pure restoring force toward planarity,
harmonic + quartic in ``chi`` (``k|c| s + k s^2 / 2``), which is also what an sp2 center would
use. For NH3 the second regime is the one that fits: the cosine angles alone already give a
double well, but its barrier, the umbrella (A1) frequency and the E bend all come from the
same ``(theta_eq, k_theta)`` and cannot all be right (constant parameters: A1 1158 vs 1022
cm^-1, E 1611 vs 1691). A planarizing improper (``c_chi ~ -0.5``) working against a more
pyramidal ``theta_eq`` (~101 deg) decouples them and reproduces HNH, both bends and the
5.9 kcal/mol barrier with constant parameters (``scripts/fit_bonded_priors_nh3.py``).

Units: this module works in **atomic units** throughout (bohr, hartree). The model converts
its Angstrom geometry once at the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn as nn

from ...mlip.heads import mlp, zero_init_readout
from ..pairs import intra_fragment_channels
from ..units import BOHR_ANG
from .state import StateDescriptor

__all__ = [
    "BondedParameterHead",
    "BondedParameters",
    "BondedTopology",
    "DEFAULT_ANGLE_PRIOR",
    "DEFAULT_BOND_PRIOR",
    "DEFAULT_IMPROPER_PRIOR",
    "cosine_angle_energy",
    "improper_energy",
    "morse_energy",
    "wilson_improper_energy",
]


# NH3 bonded priors (scripts/fit_bonded_priors_nh3.py, against HNH 106.7 deg, harmonic
# w1..w4 = 3506/1022/3577/1691 cm^-1 and a 5.9 kcal/mol inversion barrier). The angle prior
# depends on whether the improper is there to share the bending work, hence two sets.
NH3_THETA_EQ, NH3_K_THETA = 1.878044, 0.1538              # angles only (107.60 deg)
NH3_THETA_EQ_IMP, NH3_K_THETA_IMP = 1.760165, 0.1919      # with the improper (100.85 deg)
NH3_C_CHI, NH3_K_CHI = -0.5050, 0.0077                    # improper: c_chi, k_chi [Ha]

# pyCMM water (scripts/water.xml), atomic units: the validated starting point. Keys are
# unordered atomic-number pairs for bonds and the apex atomic number for angles. Pairs not
# listed fall back to GENERIC_*, which only matters once fragments beyond water appear.
DEFAULT_BOND_PRIOR: dict[tuple[int, int], tuple[float, float, float]] = {
    # (Z_a, Z_b) sorted: (r_eq [bohr], D [Ha], k [Ha/bohr^2])
    (1, 8): (1.81211318, 0.19968199, 0.54375456),
    # N-H (NH3): r_e 1.012 A; D = TAE_e(NH3)/3 (~297 kcal/mol / 3), since the well-referenced
    # Morse carries the atomization energy; k from the NH3 harmonic stretches (w1 3506, w3
    # 3577 cm^-1) with the improper/angle priors below -- scripts/fit_bonded_priors_nh3.py.
    (1, 7): (1.91240, 0.158, 0.4503),
    # H-F: r_e 0.9168 A, D_e 6.12 eV (= TAE_e of HF), k_e 9.66 mdyn/A (w_e 4138 cm^-1).
    (1, 9): (1.73250, 0.2249, 0.6205),
}
GENERIC_BOND_PRIOR: tuple[float, float, float] = (2.2, 0.15, 0.40)

DEFAULT_ANGLE_PRIOR: dict[int, tuple[float, float]] = {
    # apex Z: (theta_eq [rad], k_theta [Ha])
    8: (1.822532146, 0.1722274),
    # N apex (H-N-H): fitted together with the N improper prior below so that the bonded
    # NH3 reproduces HNH 106.7 deg, the harmonic umbrella/E-bend (1022/1691 cm^-1) and the
    # ~5.9 kcal/mol inversion barrier -- scripts/fit_bonded_priors_nh3.py.
    7: (NH3_THETA_EQ, NH3_K_THETA),
}
GENERIC_ANGLE_PRIOR: tuple[float, float] = (1.911, 0.15)

# Center Z: (c_chi, k_chi [Ha]) for the out-of-plane (Wilson-angle) improper, used only by a
# head built with ``impropers=True``. For scale: equilibrium NH3 has sin^2 chi = 0.768
# (chi = 61.2 deg -- measured from the plane of the *other two bonds*, not the H3 plane).
DEFAULT_IMPROPER_PRIOR: dict[int, tuple[float, float]] = {
    7: (NH3_C_CHI, NH3_K_CHI),
}
# An unlisted degree-3 center (the O of H3O+) starts essentially inert.
GENERIC_IMPROPER_PRIOR: tuple[float, float] = (0.0, 1.0e-3)

# Angle priors that replace DEFAULT_ANGLE_PRIOR entries when the head has impropers.
IMPROPER_ANGLE_PRIOR: dict[int, tuple[float, float]] = {
    7: (NH3_THETA_EQ_IMP, NH3_K_THETA_IMP),
}


# ---------------------------------------------------------------------------------------
# (Z, degree)-typed priors -- used only by heads built with ``atom_typing="degree"``.
#
# An atom's type is its element plus its covalent degree (``BondedTopology.degree``): read off
# the graph, so it is resonance-safe (both carboxylate O's are (8, 1)) while separating C=O
# (O deg 1) from C-O (O deg 2), carbonyl/ethene C (6, 3) from methyl C (6, 4), and so on.
# Lookup order: typed key -> element key (the tables above) -> generic. These are starting
# points from typical bond lengths, bond energies and stretch/bend force constants (the
# constant-parameter fit replaces them); D is the bond-dissociation scale the well-referenced
# Morse carries. Units: bohr, hartree.
# ---------------------------------------------------------------------------------------

_ANG = 1.0 / 0.529177210903     # bohr per Angstrom
_KCAL = 1.0 / 627.509474        # hartree per kcal/mol
_MDYN = 0.0642231               # (hartree/bohr^2) per (mdyn/Angstrom)


def _bp(r_ang: float, d_kcal: float, k_mdyn: float) -> tuple[float, float, float]:
    return (r_ang * _ANG, d_kcal * _KCAL, k_mdyn * _MDYN)


#: element-pair bond priors for the organic set (added to DEFAULT_BOND_PRIOR's water/NH3/HF)
ORGANIC_BOND_PRIOR: dict[tuple[int, int], tuple[float, float, float]] = {
    (1, 6): _bp(1.090, 105.0, 4.9),
    (6, 6): _bp(1.530, 88.0, 4.5),
    (6, 7): _bp(1.470, 83.0, 4.8),
    (6, 8): _bp(1.420, 92.0, 5.0),
    (6, 9): _bp(1.380, 110.0, 5.8),
    (6, 16): _bp(1.820, 73.0, 3.0),
    (6, 17): _bp(1.780, 84.0, 3.4),
    (1, 16): _bp(1.340, 87.0, 4.0),
    (7, 9): _bp(1.400, 67.0, 4.3),
    (8, 15): _bp(1.600, 90.0, 6.0),
}

#: typed overrides, keyed by the sorted pair of (Z, degree) types
TYPED_BOND_PRIOR: dict[tuple[tuple[int, int], tuple[int, int]], tuple[float, float, float]] = {
    ((6, 3), (6, 3)): _bp(1.330, 174.0, 9.6),     # C=C
    ((6, 3), (8, 1)): _bp(1.215, 178.0, 12.0),    # C=O (and carboxylate C-O, bond order 1.5)
    ((8, 1), (15, 4)): _bp(1.500, 130.0, 9.0),    # P=O / P-O(-)
    ((6, 3), (7, 3)): _bp(1.360, 100.0, 6.5),     # amide C-N
}

#: angle priors by apex type: (theta_eq [rad], k_theta [Ha], cosine form)
TYPED_ANGLE_PRIOR: dict[tuple[int, int], tuple[float, float]] = {
    (6, 4): (1.9106, 0.142),       # sp3 C, 109.47 deg
    (6, 3): (2.0944, 0.184),       # sp2 C, 120 deg
    (7, 4): (1.9106, 0.142),       # ammonium N
    (8, 3): (1.9400, 0.150),       # hydronium O, ~111 deg
    (15, 4): (1.9106, 0.142),      # phosphate P
    (16, 2): (1.6755, 0.120),      # thiol S, ~96 deg
}

#: out-of-plane priors by center type: (c_chi, k_chi [Ha]); c < 0 restores planarity
TYPED_IMPROPER_PRIOR: dict[tuple[int, int], tuple[float, float]] = {
    (6, 3): (-0.5, 0.08),          # sp2 C: planar
    (8, 3): (-0.5, 0.005),         # hydronium: shallow pyramid
}

MAX_DEGREE = 4


def morse_energy(
    r: torch.Tensor, r_eq: torch.Tensor, d: torch.Tensor, k: torch.Tensor
) -> torch.Tensor:
    """Well-referenced Morse: ``D [(1 - e^{-beta (r - r_eq)})^2 - 1]``, ``beta = sqrt(k/2D)``.

    Zero as ``r -> inf`` and ``-D`` at the minimum, so the sum over bonds is (minus) the
    energy of formation relative to the separated-atom reference. All inputs in a.u.
    """
    beta = torch.sqrt(k / (2.0 * d))
    x = 1.0 - torch.exp(-beta * (r - r_eq))
    return d * (x * x - 1.0)


def cosine_angle_energy(
    cos_theta: torch.Tensor, cos_theta_eq: torch.Tensor, k_theta: torch.Tensor
) -> torch.Tensor:
    """``(k_theta / 2)(cos theta - cos theta_eq)^2`` -- pyCMM's cosine-harmonic angle.

    Works on cosines throughout (no ``acos``), so it is smooth through linear geometries and
    the gradient needs no special-casing at ``theta = pi``.
    """
    diff = cos_theta - cos_theta_eq
    return 0.5 * k_theta * diff * diff


def wilson_improper_energy(
    sin2_chi: torch.Tensor, c_chi: torch.Tensor, k_chi: torch.Tensor
) -> torch.Tensor:
    """``(k_chi / 2) s (s - 2 c_chi)`` with ``s = sin^2 chi``: zero at planarity, even in chi.

    ``c_chi > 0``: double well, minima ``-k c^2/2`` at ``s = c``; ``c_chi <= 0``: restoring
    toward planarity. See the module docstring.
    """
    return 0.5 * k_chi * sin2_chi * (sin2_chi - 2.0 * c_chi)


def _impropers_from_bonds(bond_index: torch.Tensor, n_atoms: int) -> torch.Tensor:
    """``(4, Ni)`` rows ``[center, leg, j, k]``: three legs per atom of bond-degree exactly 3.

    ``j, k`` are the leg's two in-plane partners, in cyclic order (the term is even in their
    exchange, so the order is immaterial). Atoms of any other degree get no improper: a
    tetrahedral center (CH4, NH4+) needs none, and water's O (degree 2) has none, so water
    topologies are unchanged.
    """
    device = bond_index.device
    empty = torch.zeros(4, 0, dtype=torch.long, device=device)
    if bond_index.shape[1] == 0:
        return empty
    atoms = torch.cat((bond_index[0], bond_index[1]))
    others = torch.cat((bond_index[1], bond_index[0]))
    order = torch.argsort(atoms, stable=True)
    atoms_s, others_s = atoms[order], others[order]
    counts = torch.bincount(atoms_s, minlength=n_atoms)
    centers = torch.nonzero(counts == 3).flatten()
    if centers.numel() == 0:
        return empty
    offsets = torch.cumsum(counts, 0) - counts
    nbr = others_s[offsets[centers].unsqueeze(1) + torch.arange(3, device=device)]  # (C, 3)
    rows = []
    for leg, j, k in ((0, 1, 2), (1, 2, 0), (2, 0, 1)):
        rows.append(torch.stack((centers, nbr[:, leg], nbr[:, j], nbr[:, k])))
    return torch.cat(rows, dim=1)


def _angles_from_bonds(bond_index: torch.Tensor, n_atoms: int) -> torch.Tensor:
    """``(3, Na)`` rows ``[i, apex, k]``: every pair of bonds sharing an atom.

    Vectorized with the same padded-triangle trick as
    :func:`rsfff.ff.pairs.intra_fragment_channels`: build the (atom -> bonded neighbor)
    incidence sorted by atom, enumerate the upper triangle of the largest degree once, and
    mask each atom down to its own degree.
    """
    if bond_index.shape[1] == 0:
        return torch.zeros(3, 0, dtype=torch.long, device=bond_index.device)
    device = bond_index.device
    atoms = torch.cat((bond_index[0], bond_index[1]))
    others = torch.cat((bond_index[1], bond_index[0]))
    order = torch.argsort(atoms, stable=True)
    atoms_s, others_s = atoms[order], others[order]
    counts = torch.bincount(atoms_s, minlength=n_atoms)
    deg_max = int(counts.max())
    if deg_max < 2:
        return torch.zeros(3, 0, dtype=torch.long, device=device)
    offsets = torch.cumsum(counts, 0) - counts                       # (n_atoms,)
    a, b = torch.triu_indices(deg_max, deg_max, offset=1, device=device)
    keep = b.unsqueeze(0) < counts.unsqueeze(1)                      # (n_atoms, K)
    first = (offsets.unsqueeze(1) + a.unsqueeze(0))[keep]
    second = (offsets.unsqueeze(1) + b.unsqueeze(0))[keep]
    apex = (
        torch.arange(n_atoms, device=device).unsqueeze(1).expand(-1, a.numel())[keep]
    )
    return torch.stack((others_s[first], apex, others_s[second]))


@dataclass
class BondedTopology:
    """The covalent graph of one batch under one fragmentation state.

    ``bond_index``  : (2, Nb) atom pairs, ``i < j``.
    ``bond_frag``   : (Nb,) owning fragment (of the first atom; identical at one-hot ``C``).
    ``bond_weight`` : (Nb,) co-membership ``P_ij`` -- 1.0 at a one-hot assignment, fractional
                      along a state blend, which is the reactive-phase extension point
                      (a union of candidate bonded terms with continuous amplitudes).
    ``angle_index`` : (3, Na) rows ``[i, apex, k]``.
    ``angle_frag``  : (Na,) owning fragment of the apex.
    ``angle_weight``: (Na,) ``P_{i,apex} P_{apex,k}``.
    ``improper_index`` : (4, Ni) rows ``[center, leg, j, k]`` (degree-3 centers, 3 legs each).
    ``improper_frag``  : (Ni,) owning fragment of the center.
    ``improper_weight``: (Ni,) product of the three bonds' co-memberships.

    The improper rows are always enumerated (they cost nothing); they only carry energy when
    the parameter head was built with ``impropers=True``.
    """

    bond_index: torch.Tensor
    bond_frag: torch.Tensor
    bond_weight: torch.Tensor
    angle_index: torch.Tensor
    angle_frag: torch.Tensor
    angle_weight: torch.Tensor
    improper_index: torch.Tensor | None = None
    improper_frag: torch.Tensor | None = None
    improper_weight: torch.Tensor | None = None
    # --- the explicit-graph extensions (``rsfff.ff.film.topology``); always enumerated, they
    # only carry energy when the term heads that read them exist ---------------------------
    #: (N,) covalent degree of each atom: the second half of the (Z, degree) atom type.
    degree: torch.Tensor | None = None
    #: (2, Na) bond columns of each angle's two legs, ``[(i, apex), (apex, k)]``.
    angle_bonds: torch.Tensor | None = None
    #: (4, Nt) ``[a, b, c, d]``; (Nt,) owning fragment of ``b``; (Nt,) co-membership product.
    torsion_index: torch.Tensor | None = None
    torsion_frag: torch.Tensor | None = None
    torsion_weight: torch.Tensor | None = None
    #: (3, Nt) bond columns ``[ab, bc, cd]``; (2, Nt) angle columns ``[abc, bcd]``.
    torsion_bonds: torch.Tensor | None = None
    torsion_angles: torch.Tensor | None = None
    #: (4, Naa) ``[apex, s, x, y]``; (2, Naa) angle columns of ``(s, apex, x)``/``(s, apex, y)``.
    angle_pair_index: torch.Tensor | None = None
    angle_pair_angles: torch.Tensor | None = None
    angle_pair_frag: torch.Tensor | None = None
    angle_pair_weight: torch.Tensor | None = None

    @property
    def n_impropers(self) -> int:
        return 0 if self.improper_index is None else int(self.improper_index.shape[1])

    @property
    def n_torsions(self) -> int:
        return 0 if self.torsion_index is None else int(self.torsion_index.shape[1])

    @property
    def n_angle_pairs(self) -> int:
        return 0 if self.angle_pair_index is None else int(self.angle_pair_index.shape[1])

    @classmethod
    def from_state(
        cls,
        state: StateDescriptor,
        atomic_numbers: torch.Tensor,
        bonds: torch.Tensor | None = None,
    ) -> "BondedTopology":
        """Enumerate the bonded terms from the covalent graph -- no distance anywhere.

        ``bonds`` (2, Nc), global atom indices: the **explicit** covalent graph the data
        carries (``Batch.covalent_bonds``). It is the only correct source once a fragment has
        more than one heavy atom -- the legacy rule below would bond ethane's methyl H's to
        the far carbon. ``None`` falls back to that rule: every intra-fragment pair that is
        not H-H, which is exact for water, HF, NH3, H3O+, OH- and their clusters (the loader
        refuses a multi-heavy-atom fragment without bonds).

        Angles come from bonds sharing an atom; torsions, angle pairs and impropers likewise
        (``rsfff.ff.film.topology``). For a water that is exactly 2 x (O, H) and 1 x (H, O, H)
        and nothing else, as before.
        """
        from .topology import (
            angle_pairs_from_angles, atom_degrees, canonical_bonds, lookup_angles,
            lookup_bonds, torsions_from_bonds,
        )

        n_atoms = int(atomic_numbers.shape[0])
        if bonds is None:
            pairs, _ = intra_fragment_channels(state.fragment_idx)
            is_h = atomic_numbers == 1
            keep = ~(is_h[pairs[0]] & is_h[pairs[1]])
            bond_index = pairs[:, keep]
        else:
            bond_index = canonical_bonds(bonds.to(state.fragment_idx.device))
        bond_frag = state.fragment_idx[bond_index[0]]
        bond_weight = state.edge_comembership(bond_index)

        def comem(a, b):
            return (state.C[a] * state.C[b]).sum(-1)

        angle_index = _angles_from_bonds(bond_index, n_atoms)
        angle_frag = state.fragment_idx[angle_index[1]]
        i, apex, k = angle_index[0], angle_index[1], angle_index[2]
        angle_weight = comem(i, apex) * comem(apex, k)

        improper_index = _impropers_from_bonds(bond_index, n_atoms)
        c = improper_index[0]
        improper_frag = state.fragment_idx[c]
        improper_weight = torch.ones_like(improper_frag, dtype=state.C.dtype)
        for row in (1, 2, 3):
            improper_weight = improper_weight * comem(c, improper_index[row])

        angle_bonds = torch.stack((
            lookup_bonds(bond_index, n_atoms, i, apex),
            lookup_bonds(bond_index, n_atoms, apex, k),
        )) if angle_index.shape[1] else angle_index.new_zeros(2, 0)

        torsion_index = torsions_from_bonds(bond_index, n_atoms)
        ta, tb, tc, td = (torsion_index[r] for r in range(4))
        torsion_frag = state.fragment_idx[tb]
        torsion_weight = comem(ta, tb) * comem(tb, tc) * comem(tc, td)
        if torsion_index.shape[1]:
            torsion_bonds = torch.stack((
                lookup_bonds(bond_index, n_atoms, ta, tb),
                lookup_bonds(bond_index, n_atoms, tb, tc),
                lookup_bonds(bond_index, n_atoms, tc, td),
            ))
            torsion_angles = torch.stack((
                lookup_angles(angle_index, n_atoms, ta, tb, tc),
                lookup_angles(angle_index, n_atoms, tb, tc, td),
            ))
        else:
            torsion_bonds = torsion_index.new_zeros(3, 0)
            torsion_angles = torsion_index.new_zeros(2, 0)

        angle_pair_index = angle_pairs_from_angles(bond_index, n_atoms)
        pa, ps, px, py = (angle_pair_index[r] for r in range(4))
        angle_pair_frag = state.fragment_idx[pa]
        angle_pair_weight = comem(pa, ps) * comem(pa, px) * comem(pa, py)
        angle_pair_angles = torch.stack((
            lookup_angles(angle_index, n_atoms, ps, pa, px),
            lookup_angles(angle_index, n_atoms, ps, pa, py),
        )) if angle_pair_index.shape[1] else angle_pair_index.new_zeros(2, 0)

        return cls(
            bond_index=bond_index,
            bond_frag=bond_frag,
            bond_weight=bond_weight,
            angle_index=angle_index,
            angle_frag=angle_frag,
            angle_weight=angle_weight,
            improper_index=improper_index,
            improper_frag=improper_frag,
            improper_weight=improper_weight,
            degree=atom_degrees(bond_index, n_atoms),
            angle_bonds=angle_bonds,
            torsion_index=torsion_index,
            torsion_frag=torsion_frag,
            torsion_weight=torsion_weight,
            torsion_bonds=torsion_bonds,
            torsion_angles=torsion_angles,
            angle_pair_index=angle_pair_index,
            angle_pair_angles=angle_pair_angles,
            angle_pair_frag=angle_pair_frag,
            angle_pair_weight=angle_pair_weight,
        )

    def separation(self, pair_index: torch.Tensor, n_atoms: int, max_sep: int = 3) -> torch.Tensor:
        """``(P,)`` graph separation of each pair (1 = 1-2, 2 = 1-3, 3 = 1-4, ``max_sep+1`` beyond)."""
        from .topology import graph_separation

        return graph_separation(self.bond_index, n_atoms, pair_index, max_sep)

    def exclusions(self, n_atoms: int, through: int = 3) -> torch.Tensor:
        """``(2, E)`` atom pairs ``i < j`` within ``through - 1`` bonds of each other.

        The classical-force-field exclusion list: ``through=3`` is every 1-2 and 1-3 pair,
        ``through=4`` adds the 1-4 pairs. Read off the covalent graph (``bond_index``), so
        like the bonds themselves it comes from the fragment assignment and never from a
        distance: a stretched bond cannot drop out of its own exclusion.

        Enumerated as walks on the bond graph from every atom, one hop at a time through a
        padded neighbor table. Walks may backtrack, which only revisits pairs already at a
        shorter separation; ``unique`` removes the repeats and the self pairs are dropped.
        """
        device = self.bond_index.device
        empty = torch.zeros(2, 0, dtype=torch.long, device=device)
        hops = int(through) - 1
        if hops < 1 or self.bond_index.shape[1] == 0:
            return empty
        atoms = torch.cat((self.bond_index[0], self.bond_index[1]))
        others = torch.cat((self.bond_index[1], self.bond_index[0]))
        order = torch.argsort(atoms, stable=True)
        atoms_s, others_s = atoms[order], others[order]
        counts = torch.bincount(atoms_s, minlength=n_atoms)
        deg_max = int(counts.max())
        offsets = torch.cumsum(counts, 0) - counts
        slot = torch.arange(atoms_s.numel(), device=device) - offsets[atoms_s]
        nbr = torch.full((n_atoms, deg_max), -1, dtype=torch.long, device=device)
        nbr[atoms_s, slot] = others_s                                  # (n_atoms, deg_max)

        src, dst = atoms_s, others_s                                   # walks of length 1
        found = [torch.stack((src, dst))]
        for _ in range(hops - 1):
            nxt = nbr[dst]                                             # (W, deg_max)
            keep = nxt >= 0
            src = src.unsqueeze(1).expand_as(nxt)[keep]
            dst = nxt[keep]
            found.append(torch.stack((src, dst)))
        pairs = torch.cat(found, dim=1)
        pairs = pairs[:, pairs[0] != pairs[1]]
        lo = torch.minimum(pairs[0], pairs[1])
        hi = torch.maximum(pairs[0], pairs[1])
        keys = torch.unique(lo * n_atoms + hi)
        return torch.stack((keys // n_atoms, keys % n_atoms))

    def geometry(self, positions_ang: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """``(r_bohr (Nb,), cos_theta (Na,))`` from Angstrom positions, differentiably."""
        i, j = self.bond_index[0], self.bond_index[1]
        r = (positions_ang[i] - positions_ang[j]).norm(dim=-1) / BOHR_ANG
        a, apex, c = self.angle_index[0], self.angle_index[1], self.angle_index[2]
        v1 = positions_ang[a] - positions_ang[apex]
        v2 = positions_ang[c] - positions_ang[apex]
        cos_theta = (v1 * v2).sum(-1) / (v1.norm(dim=-1) * v2.norm(dim=-1))
        return r, cos_theta

    def torsion_cos(self, positions_ang: torch.Tensor, eps: float = 1e-12) -> torch.Tensor:
        """``(Nt,)`` ``cos phi`` of every torsion, differentiably and without ``acos``.

        ``cos phi = n1.n2 / (|n1||n2|)`` with ``n1 = b1 x b2``, ``n2 = b2 x b3``. Every
        torsion energy here is a polynomial in ``cos phi`` (``cos n phi = T_n(cos phi)``), so
        nothing is singular at ``phi = 0, pi``; the only undefined point is a collinear
        triple, guarded by ``eps``.
        """
        a, b, c, d = (self.torsion_index[n] for n in range(4))
        b1 = positions_ang[b] - positions_ang[a]
        b2 = positions_ang[c] - positions_ang[b]
        b3 = positions_ang[d] - positions_ang[c]
        n1 = torch.cross(b1, b2, dim=-1)
        n2 = torch.cross(b2, b3, dim=-1)
        norm = torch.sqrt((n1 * n1).sum(-1).clamp_min(eps) * (n2 * n2).sum(-1).clamp_min(eps))
        return (n1 * n2).sum(-1) / norm

    def improper_sin2(self, positions_ang: torch.Tensor, eps: float = 1e-10) -> torch.Tensor:
        """``(Ni,)`` ``sin^2 chi`` of every improper leg, differentiably (dimensionless).

        ``sin chi = b_l . (b_j x b_k) / |b_j x b_k|`` with unit bond vectors from the center;
        squared, so it is even in the inversion and in the ``j <-> k`` exchange. Always in
        ``[0, 1]``; the ``eps`` floor guards only the degenerate ``b_j || b_k`` case.
        """
        c, leg, j, k = (self.improper_index[n] for n in range(4))
        x = positions_ang[c]

        def unit(v):
            return v / v.norm(dim=-1, keepdim=True)

        bl, bj, bk = unit(positions_ang[leg] - x), unit(positions_ang[j] - x), unit(positions_ang[k] - x)
        n = torch.cross(bj, bk, dim=-1)
        triple = (bl * n).sum(-1)
        return triple * triple / (n * n).sum(-1).clamp_min(eps)


@dataclass
class BondedParameters:
    """One evaluation's bonded parameters plus the raw deviations the regularizer reads.

    ``r_eq, d, k``          : (Nb,) Morse parameters, a.u.
    ``cos_theta_eq, k_theta``: (Na,) angle parameters.
    ``delta_iso``           : flat tensor of the feature-dependent log/raw deviations from
                              the per-type tables at the *isolated* branch -- the quantity the
                              geometry-independence penalty pulls toward zero. (The env
                              deviation is governed by the induction label and the L1 env
                              penalty instead, and is not included here.)
    """

    r_eq: torch.Tensor
    d: torch.Tensor
    k: torch.Tensor
    cos_theta_eq: torch.Tensor
    k_theta: torch.Tensor
    delta_iso: torch.Tensor | None = None
    c_chi: torch.Tensor | None = None           # (Ni,) None unless the head has impropers
    k_chi: torch.Tensor | None = None           # (Ni,) Ha

    def energy(
        self, r: torch.Tensor, cos_theta: torch.Tensor, topo: BondedTopology
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """``(per-bond (Nb,), per-angle (Na,))`` energies, co-membership weighted."""
        e_bond = topo.bond_weight * morse_energy(r, self.r_eq, self.d, self.k)
        e_angle = topo.angle_weight * cosine_angle_energy(
            cos_theta, self.cos_theta_eq, self.k_theta
        )
        return e_bond, e_angle

    def improper_energy(self, sin2_chi: torch.Tensor, topo: BondedTopology) -> torch.Tensor:
        """``(Ni,)`` co-membership-weighted out-of-plane energies."""
        return topo.improper_weight * wilson_improper_energy(sin2_chi, self.c_chi, self.k_chi)


def improper_energy(
    positions_ang: torch.Tensor, topo: BondedTopology, params: BondedParameters
) -> torch.Tensor | None:
    """``(Ni,)`` improper energies, or ``None`` when the head carries no improper parameters
    or the batch has no degree-3 center. Plain torch on every backend (a handful of terms per
    molecule; double backward comes from autograd)."""
    if params.c_chi is None or topo.n_impropers == 0:
        return None
    return params.improper_energy(topo.improper_sin2(positions_ang), topo)


class BondedParameterHead(nn.Module):
    """Per-bond ``(r_eq, D, k)``, per-angle ``(theta_eq, k_theta)`` and, with
    ``impropers=True``, per-improper-leg ``(c_chi, k_chi)`` from the latents.

    Every parameter is ``table[type] * exp(delta_iso + gate * delta_env)`` (positives) or
    ``tanh(table[type] + delta_iso + gate * delta_env)`` (``cos theta_eq``), with:

    - a **learnable per-type table** initialized at the pyCMM water values, so a fresh model
      *is* pyCMM water and the readouts start at exactly zero deviation;
    - ``delta_iso`` from the isolated latent -- the geometry dependence the variance
      regularizer disciplines;
    - ``delta_env`` from the joined latent, zero-initialized and multiplied by the
      environment gate, so it vanishes exactly for an isolated fragment. Its energy lands in
      the induction channel (``E_bonded(theta) - E_bonded(theta_0)``) -- the learned analogue
      of pyCMM's field-dependent Morse.

    **Geometry enters only through the features.** The heads never see ``r`` or ``theta``;
    feeding them the coordinate a parameter multiplies would make the "parameter" a disguised
    pair energy and the physical form a fiction.

    Inputs are symmetric functions of the endpoint latents (``z_i + z_j``, ``(z_i - z_j)^2``
    -- squared, not ``| |``, so the symmetric-geometry point is smooth), which makes the
    parameters invariant under within-fragment permutation of identical atoms by
    construction.
    """

    def __init__(
        self,
        latent_dim: int,
        species: list[int],
        *,
        hidden: int = 64,
        depth: int = 1,
        emb_dim: int = 8,
        bond_prior: dict[tuple[int, int], tuple[float, float, float]] | None = None,
        angle_prior: dict[int, tuple[float, float]] | None = None,
        impropers: bool = False,
        improper_prior: dict[int, tuple[float, float]] | None = None,
        atom_typing: str = "element",
    ) -> None:
        super().__init__()
        self.species = [int(z) for z in species]
        if atom_typing not in ("element", "degree"):
            raise ValueError(f"atom_typing must be 'element' or 'degree', got {atom_typing!r}")
        self.atom_typing = atom_typing
        # The table axis: one row per species ("element", every existing checkpoint) or one
        # per (species, degree 0..MAX_DEGREE) ("degree"). `_type_index` maps atoms onto it.
        if atom_typing == "degree":
            types = [(z, d) for z in self.species for d in range(MAX_DEGREE + 1)]
        else:
            types = [(z, None) for z in self.species]
        self.types = types
        n_species = len(types)

        def bond_lookup(ta, tb):
            (za, da), (zb, db) = sorted((ta, tb), key=lambda t: (t[0], -1 if t[1] is None else t[1]))
            if da is not None:
                key = tuple(sorted(((za, da), (zb, db))))
                if key in TYPED_BOND_PRIOR:
                    return TYPED_BOND_PRIOR[key]
            ekey = (min(za, zb), max(za, zb))
            return bond_prior.get(ekey, GENERIC_BOND_PRIOR)

        def apex_lookup(t, typed_table, element_table, generic):
            z, d = t
            if d is not None and (z, d) in typed_table:
                return typed_table[(z, d)]
            return element_table.get(z, generic)

        # {**a, **b} rather than dict(a, **b): the keys are ints / int tuples, not strings
        bond_prior = {**ORGANIC_BOND_PRIOR, **DEFAULT_BOND_PRIOR, **(bond_prior or {})}
        angle_prior = {
            **DEFAULT_ANGLE_PRIOR,
            **(IMPROPER_ANGLE_PRIOR if impropers else {}),
            **(angle_prior or {}),
        }

        # (n_species, n_species, 3) log-parameter table, symmetric by construction (filled
        # for both orderings). Learnable: the table is the geometry-independent part of every
        # parameter, i.e. the analytic minimum of the variance penalty.
        table = torch.empty(n_species, n_species, 3)
        for ia, ta in enumerate(types):
            for ib, tb in enumerate(types):
                r_eq, d, k = bond_lookup(ta, tb)
                table[ia, ib] = torch.tensor([r_eq, d, k]).log()
        self.bond_table = nn.Parameter(table)

        # (n_species, 2): [atanh(cos theta_eq), log k_theta] per apex species.
        atable = torch.empty(n_species, 2)
        for ia, ta in enumerate(types):
            theta_eq, k_theta = apex_lookup(
                ta, TYPED_ANGLE_PRIOR, angle_prior, GENERIC_ANGLE_PRIOR,
            )
            atable[ia, 0] = torch.atanh(torch.tensor(theta_eq).cos())
            atable[ia, 1] = torch.tensor(k_theta).log()
        self.angle_table = nn.Parameter(atable)

        self.species_emb = nn.Embedding(n_species, emb_dim)
        bond_in = 2 * latent_dim + 2 * emb_dim
        angle_in = 3 * latent_dim + 3 * emb_dim
        self.bond_base = zero_init_readout(mlp(bond_in, hidden, depth, 3))
        self.bond_delta = zero_init_readout(mlp(bond_in, hidden, depth, 3))
        self.angle_base = zero_init_readout(mlp(angle_in, hidden, depth, 2))
        self.angle_delta = zero_init_readout(mlp(angle_in, hidden, depth, 2))

        # Out-of-plane impropers, opt-in so that heads built without them (every water
        # checkpoint) keep their exact parameter set and initialization order.
        # (n_species, 2): [atanh(c_chi), log k_chi] per center species.
        self.impropers = bool(impropers)
        if self.impropers:
            improper_prior = {**DEFAULT_IMPROPER_PRIOR, **(improper_prior or {})}
            itable = torch.empty(n_species, 2)
            for ia, ta in enumerate(types):
                c_chi, k_chi = apex_lookup(
                    ta, TYPED_IMPROPER_PRIOR, improper_prior, GENERIC_IMPROPER_PRIOR
                )
                c_chi = min(max(float(c_chi), -0.999), 0.999)
                itable[ia, 0] = torch.atanh(torch.tensor(c_chi))
                itable[ia, 1] = torch.tensor(max(float(k_chi), 1e-8)).log()
            self.improper_table = nn.Parameter(itable)
            improper_in = 4 * latent_dim + 4 * emb_dim
            self.improper_base = zero_init_readout(mlp(improper_in, hidden, depth, 2))
            self.improper_delta = zero_init_readout(mlp(improper_in, hidden, depth, 2))

    def type_index(self, species_idx: torch.Tensor, topo: BondedTopology) -> torch.Tensor:
        """``(N,)`` row of the prior tables: the species, or (species, degree) when typed."""
        if self.atom_typing == "element":
            return species_idx
        if topo.degree is None:
            raise ValueError("atom_typing='degree' needs BondedTopology.degree")
        return species_idx * (MAX_DEGREE + 1) + topo.degree.clamp(max=MAX_DEGREE)

    def _bond_input(self, z: torch.Tensor, species_idx: torch.Tensor, topo) -> torch.Tensor:
        i, j = topo.bond_index[0], topo.bond_index[1]
        emb = self.species_emb(species_idx)
        zi, zj = z[i], z[j]
        return torch.cat(
            ((zi + zj), (zi - zj) ** 2, emb[i] + emb[j], (emb[i] - emb[j]) ** 2), dim=-1
        )

    def _angle_input(self, z: torch.Tensor, species_idx: torch.Tensor, topo) -> torch.Tensor:
        a, apex, c = topo.angle_index[0], topo.angle_index[1], topo.angle_index[2]
        emb = self.species_emb(species_idx)
        za, zc = z[a], z[c]
        return torch.cat(
            (
                z[apex], (za + zc), (za - zc) ** 2,
                emb[apex], emb[a] + emb[c], (emb[a] - emb[c]) ** 2,
            ),
            dim=-1,
        )

    def _improper_input(self, z: torch.Tensor, species_idx: torch.Tensor, topo) -> torch.Tensor:
        """Center, leg, and the symmetric pair of in-plane partners -- invariant to ``j <-> k``."""
        c, leg, j, k = (topo.improper_index[n] for n in range(4))
        emb = self.species_emb(species_idx)
        zj, zk = z[j], z[k]
        return torch.cat(
            (
                z[c], z[leg], (zj + zk), (zj - zk) ** 2,
                emb[c], emb[leg], emb[j] + emb[k], (emb[j] - emb[k]) ** 2,
            ),
            dim=-1,
        )

    def forward(
        self,
        z_iso: torch.Tensor,          # (N, latent)
        z_joined: torch.Tensor | None,  # (N, latent) or None for the isolated evaluation
        gate: torch.Tensor | None,    # (N,) environment gate g(a_env), g(0) = 0
        species_idx: torch.Tensor,    # (N,)
        topo: BondedTopology,
        z_shift: torch.Tensor | None = None,  # (N, latent) field shift, dressed eval only
    ) -> BondedParameters:
        """Parameters at one evaluation. ``z_joined=None`` gives ``theta_0`` exactly.

        Note ``theta_0`` needs no separate machinery: the delta branch is *multiplied by the
        gate*, so on an isolated fragment ``theta == theta_0`` bitwise regardless of weights.
        """
        species_idx = self.type_index(species_idx, topo)
        if z_shift is not None and z_joined is not None:
            # the field-dressed evaluation: the isolated branch reads the shifted latent
            # (rsfff.ff.film.fields; the shift is O(F^2) by construction and None in vacuum)
            z_iso = z_iso + z_shift
        bond_x_iso = self._bond_input(z_iso, species_idx, topo)
        angle_x_iso = self._angle_input(z_iso, species_idx, topo)
        d_bond = self.bond_base(bond_x_iso)                        # (Nb, 3)
        d_angle = self.angle_base(angle_x_iso)                     # (Na, 2)
        with_improper = self.impropers and topo.n_impropers > 0
        if with_improper:
            d_imp = self.improper_base(self._improper_input(z_iso, species_idx, topo))
            delta_iso = torch.cat(
                (d_bond.reshape(-1), d_angle.reshape(-1), d_imp.reshape(-1))
            )
        else:
            delta_iso = torch.cat((d_bond.reshape(-1), d_angle.reshape(-1)))

        if z_joined is not None:
            if gate is None:
                raise ValueError("the env-dressed evaluation needs the environment gate")
            i, j = topo.bond_index[0], topo.bond_index[1]
            g_bond = 0.5 * (gate[i] + gate[j])
            a, apex, c = topo.angle_index[0], topo.angle_index[1], topo.angle_index[2]
            g_angle = (gate[a] + gate[apex] + gate[c]) / 3.0
            d_bond = d_bond + g_bond.unsqueeze(-1) * self.bond_delta(
                self._bond_input(z_joined, species_idx, topo)
            )
            d_angle = d_angle + g_angle.unsqueeze(-1) * self.angle_delta(
                self._angle_input(z_joined, species_idx, topo)
            )
            if with_improper:
                g_imp = sum(gate[topo.improper_index[n]] for n in range(4)) / 4.0
                d_imp = d_imp + g_imp.unsqueeze(-1) * self.improper_delta(
                    self._improper_input(z_joined, species_idx, topo)
                )

        si = species_idx[topo.bond_index[0]]
        sj = species_idx[topo.bond_index[1]]
        if self.atom_typing == "degree":
            # canonical orientation, so the (learnable, separately-updated) [a, b] and [b, a]
            # entries can never make the energy depend on which atom is stored first. The
            # element-typed path keeps its legacy lookup: existing checkpoints trained only
            # the storage-order entry (O before H in every water file).
            si, sj = torch.minimum(si, sj), torch.maximum(si, sj)
        log_bond = self.bond_table[si, sj] + d_bond                # (Nb, 3)
        r_eq, d, k = log_bond.exp().unbind(-1)

        s_apex = species_idx[topo.angle_index[1]]
        raw_angle = self.angle_table[s_apex] + d_angle             # (Na, 2)
        cos_theta_eq = torch.tanh(raw_angle[:, 0])
        k_theta = raw_angle[:, 1].exp()

        c_chi = k_chi = None
        if self.impropers:
            if with_improper:
                s_c = species_idx[topo.improper_index[0]]
                raw_imp = self.improper_table[s_c] + d_imp             # (Ni, 2)
            else:  # keep the fields typed (and the improper path uniform) on empty batches
                raw_imp = self.improper_table.new_zeros(0, 2)
            c_chi = torch.tanh(raw_imp[:, 0])
            k_chi = raw_imp[:, 1].exp()

        return BondedParameters(
            r_eq=r_eq, d=d, k=k,
            cos_theta_eq=cos_theta_eq, k_theta=k_theta,
            delta_iso=delta_iso,
            c_chi=c_chi, k_chi=k_chi,
        )
